### ISSUE TITLE
Placing and replacing Monitoring Crystals in the same location duplicates messages

### ISSUE THREAD

**Issue by democat3457** [AranaiRa/ArcaneArchives#100]
After placing a Monitoring Crystal on a storage and replacing it, when opening a Manifest of Manifest Lectern, the chat will spam messages repeatedly regarding "Multiple Monitoring Crystals were found targeting the same block."

Image here: https://imgur.com/NDnxRxO

Originally reported at https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/410

**Comment by noobanidus** [comment]
Which version of Arcane Archives are you running in your pack?

**Comment by democat3457** [comment]
0.2.0.19

**Comment by noobanidus** [comment]
Interesting. It sounds as though the initial monitoring crystal tile entity isn't being de-registered. I'll look into it.

**Comment by noobanidus** [comment]
Release 21 (choose your mixins version) should resolve this.
