### ISSUE TITLE
latest version crashes on startup

### ISSUE THREAD

**Issue by FrostCreeper07** [AranaiRa/ArcaneArchives#101]
The latest version of Arcane Archives (arcanearchives-0.2.0.20-mixins7.11) crashes on startup with ModLoader not Available, i was able to get it working again by downgrading to the previous version, thought you might want to know [here](https://pastebin.com/U5VEJszv) (Not Really a Crashlog but it might help)

**Comment by noobanidus** [comment]
I'm pretty sure there's a note in the page stating to try a different version if there's a mixins-related crash.
