### ISSUE TITLE
Monitoring crystals should also allow placing into external storage

### ISSUE THREAD

**Issue by TLATER** [AranaiRa/ArcaneArchives#104]
I looked through the issues but didn't see this yet, though I imagine it's a popular request, so let me raise it :)

It would be nice if external storage could be connected via monitoring crystals (or some similar concept) that would allow _insertion_ as well as, well, monitoring.

My current use case is to place items into fridges for [CookingForBlockheads](https://github.com/blay09/CookingForBlockheads), since it's extremely annoying to manually filter out food items from things I dump into braziers of hoarding, but I'm sure there are a number of reasons one would want to do this.

**Comment by noobanidus** [comment]
Monitoring Crystals are *purely* for monitoring, I'm afraid. They're not designed to function as an external storage bus.

**Comment by TLATER** [comment]
> or some similar concept

Is there no place for this concept in the mod at all?

**Comment by LadyEternal** [comment]
An object which does this is currently planned for later stage networks.

**Comment by noobanidus** [comment]
Yes, sorry, I failed to include that in my original reply; there is an upcoming feature which will do something similar.

**Comment by TLATER** [comment]
Not to trample too much on how this project does things, but would you mind leaving the issue open then, even if you might want to change the title?

Typically I open feature request tickets to track:

 - If a feature is considered desirable in the first place
- Whether it is being worked on or if help would be appreciated
- The discussion on it to see how it is being implemented
- When the issue is closed so I know when to upgrade to get the feature (or make a fork because it's not being considered anymore for whatever reason)

It's much easier to jump in and contribute once it starts annoying me enough if there's an open ticket with some discussion of what this feature should look like :)

**Comment by noobanidus** [comment]
Feature discussion generally takes place on our Discord. At the minute I'm working on a number of projects, and Arcane Archives is currently in the middle of a rewrite which will eventually include a similar feature to this; there won't be any updates until I get a chance to start working on it again.

While I understand that you prefer to be able to keep an eye on issues in this fashion, this project doesn't really work like that, and having an open issue wouldn't achieve anything.
