### ISSUE TITLE
Radiant Crafting Table dupe

### ISSUE THREAD

**Issue by bigenergy** [AranaiRa/ArcaneArchives#106]
You need to go into this Radiant Crafting Table with a friend, lay out the craft and pick it up, then the friend takes this item from the cell for obtaining the crafted item.

Prevent other players from looking into the container if someone already has it open

**Comment by noobanidus** [comment]
Ah, bugger. I thought that was something that had been resolved. There are some issues with recipe updates when trying to implement fast-recipe/fast-workbench. I'll try to give it some more love and care.

**Comment by bigenergy** [comment]
@noobanidus any ideas for fix this?

**Comment by bigenergy** [comment]
@noobanidus ?

**Comment by noobanidus** [comment]
Unfortunately not as yet, I've been working on the 1.16.4 port.
