### ISSUE TITLE
Sorting in Radiant Chests is buggy

### ISSUE THREAD

**Issue by democat3457** [AranaiRa/ArcaneArchives#108]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/419

Inventory Tweaks
Happens when using the middle-click feature as well as row/column sorting.

EDIT: also Quark's merge/deposit/extract/restock feature doesn't work, although their "Deposit to Nearby Chests" feature works.

**Comment by noobanidus** [comment]
Yeah unfortunately that's an issue. We're going to add our own sort button as a solution.

**Comment by democat3457** [comment]
Ooo, nice! Will that include the merge, deposit, etc.?

**Comment by noobanidus** [comment]
Ideally yes, although merge can theoretically already be achieved via braziers. I'll have to dig into how that might work in the UI though. But yes, their "merge" UI button is different to their "Deposit to/Merge to nearby chests" button (at least as far as implementation goes -- I think).

**Comment by democat3457** [comment]
Any ETA on this sorting system?

**Comment by noobanidus** [comment]
Not for 1.12, no, sorry.
