### ISSUE TITLE
Placed blocks disappear

### ISSUE THREAD

**Issue by kave777** [AranaiRa/ArcaneArchives#109]
arcane archives  version  0.2.0.23-mixins8
minecraft 1.15.2
When i am trying to place something from mod, it disappears. And when i am trying to place radiant resonator, game crashes. 
https://paste.ee/p/HQLsy

**Comment by Zieg777** [comment]
I'm sorry, Minecraft 1.15?

Last I checked the mod was only out for 1.12

**Comment by AranaiRa** [comment]
That is correct, Arcane Archives currently only has a 1.12 version. We'll be moving ahead to more modern version after the next big release.

**Comment by noobanidus** [comment]
@kave777 This appears to be a conflict with Stack Up or AbyssalCraft.

**Comment by noobanidus** [comment]
I am gonna close this again as this is definitely an issue with either Stack Up or Abyssal Craft.
