### ISSUE TITLE
Possible Loading Crash

### ISSUE THREAD

**Issue by Dragnier** [AranaiRa/ArcaneArchives#11]
[latest.log](https://gist.github.com/Dragnier/18aab56eaf2f22971be0f6abd3d9d472)

Crashed after hitting play on the launcher without ever opening another window. Not sure if this is even ArcArc or something else, but there are a lot of Arcane Archive mentions in the log right before the crash.

**Comment by duely** [comment]
This has nothing to do with Arcane Archives. It looks as though Better Portals have a Mixin against Entity which is not being applied (as the class has already been transformed), and because of it being marked as an essential Mixin, the game crashes rather than continue launching.

**Comment by Dragnier** [comment]
Thanks, posted to them and referenced this.
