### ISSUE TITLE
Dependency missing: gbook_snapshot

### ISSUE THREAD

**Issue by ghost** [AranaiRa/ArcaneArchives#111]
I have the lastest version of guidebook (2.9.5) and this mod still says gbook_snapshot is needed.

**Comment by noobanidus** [comment]
`gbook_snapshot` is an embedded version of Guidebook that comes pre-packaged with Arcane Archives. I'm curious as what sort of set-up you have that's causing this conflict. Do you have any logs or crash reports?

**Comment by noobanidus** [comment]
Closing this as no additional information was provided.
