### ISSUE TITLE
Disconnect with Midnight mod [Bug]

### ISSUE THREAD

**Issue by Mondanzo** [AranaiRa/ArcaneArchives#113]
When running minecraft with Midnight and Arcane Archives and you try to put any kind of item into an arcane chest
the connection gets disconnected from single player as well as from a dedicated server.

[Here's a crashreport with only the exceptions thrown.](https://hastebin.com/raw/miwoduceje)

Minecraft version 1.12.2 with forge 1.4.23.5.2854
Arcane Archive version 0.2.0.24-mixins8
Midnight version 0.3.5

**Comment by noobanidus** [comment]
Please update to 0.2.0.25 of Arcane Archives, as it contains a hotfix to fix this bug. (Which is unrelated to Midnight.)
