### ISSUE TITLE
Crash While Loading After Deleting Arcane Archives

### ISSUE THREAD

**Issue by Stevphen** [AranaiRa/ArcaneArchives#116]
[crash-2020-11-15_12.45.03-client.txt](https://github.com/AranaiRa/ArcaneArchives/files/5542837/crash-2020-11-15_12.45.03-client.txt)

Hey, love the mod, but it didn't fit the theme of my current modpack so I attempted to remove it. First I deleted it on the Twitch modpack creator, but I noticed it was still showing in game. So I manually deleted the mod from the mods folder and then I got this crash report. I tried deleting gbook_snapshot, but that didn't have any effect. Not sure what else to try. Any help is appreciated.

**Comment by noobanidus** [comment]
Try deleting the "memory_repo" folder as well.

**Comment by Stevphen** [comment]
I tried deleting the memory_repo folder as well. Unfortuantely, I got the same error.

**Comment by noobanidus** [comment]
Hm, a "1.12.2" or somewhat similar folder? Basically, any folder in the mods folder (that isn't tabula) should be removed.

**Comment by Stevphen** [comment]
That did the trick. I deleted the memory_repo and the 1.12.2 folder from the mods folder and I stopped getting the error. It crashed initially but I wanted to launch it again after the replacement folders were created and then it worked.
