### ISSUE TITLE
Duplication glitch with Better With Mods block dispenser

### ISSUE THREAD

**Issue by CalaMariGold** [AranaiRa/ArcaneArchives#118]
Using current latest arcane archives version

All info here
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/604

**Comment by noobanidus** [comment]
[I've replied in that thread](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/604#issuecomment-772179721). As far as I'm concerned, the onus here is on the Better With Mods team, as I don't believe they're even interacting with any of the Arcane Archives-specific code in the itemblock.

Arcane Archives isn't programmed to support block placers (in fact, we spent quite an amount of time trying to prevent block placers from functioning earlier in the 0.2 cycle) or tile entity movers or, basically, any complex mechanism that bypasses vanilla logic/doesn't call or obey vanilla function calls.

Given that this can be solved by blacklisting the item from the block dispenser, and I see nothing in Better With Mods' code to indicate that it might be our code that's the issue, I'm going to close this.
