### ISSUE TITLE
Plans for a 1.16.5 version?

### ISSUE THREAD

**Issue by vizthex123** [AranaiRa/ArcaneArchives#122]
Would've commented on the page, but comments are disabled :c

Anyway, are there plans for a 1.16.5 version? Or something similar? Because this thematically fits my modpack better than AE2 (and RS) do, so I wanted to use it.

**Comment by AranaiRa** [comment]
A 1.16 version is currently in the works, and a first alpha is going to be ready for testing Soon™.

With that said, ArcArc isn't going to be capable of doing the type of stuff that AE and RS do (mass storage with I/O, autocrafting) for awhile yet, so unless you're keen on waiting months at minimum, you should probably consider one of the tech storage options for the time being. Or Occultism!

**Comment by vizthex123** [comment]
Alright, I actually found a few other storage mods after posting this issue. Can't wait for the update.

**Comment by Daenyth** [comment]
@vizthex123 what did you find? I'm looking to make a pack without AE/RS, or big tech mods. Looking for simple storage/crafting systems

**Comment by vizthex123** [comment]
> @vizthex123 what did you find? I'm looking to make a pack without AE/RS, or big tech mods. Looking for simple storage/crafting systems

[Storage Drawers](https://www.curseforge.com/minecraft/mc-mods/storage-drawers), [Storage Racks](https://www.curseforge.com/minecraft/mc-mods/storage-racks), etc.

I just browsed through CurseForge for a bit to find them.
