### ISSUE TITLE
any player can access chest without permission.

### ISSUE THREAD

**Issue by iceyrazor** [AranaiRa/ArcaneArchives#125]
just what the title says. without me ever adding them. any player can access the chest. they cant access the manifest though

i did try running the -mixins7 version. but my game just crashed on launch so cant do that

**Comment by LadyEternal** [comment]
chests dont currently have any sort of built-in protection like that to my knowledge. i believe this is the expected behavior.

**Comment by iceyrazor** [comment]
> chests dont currently have any sort of built-in protection like that to my knowledge. i believe this is the expected behavior.

https://youtu.be/smrwlq9LaEA?t=2218 why does this then explain that there is such a thing for multiplayer?

**Comment by AranaiRa** [comment]
There's _planned_ network security that's intended to be introduced along with the more advanced storage devices. The stuff in the mod right now is just the early game storage solutions.

**Comment by iceyrazor** [comment]
> There's _planned_ network security that's intended to be introduced along with the more advanced storage devices. The stuff in the mod right now is just the early game storage solutions.

so then. why is the person in the video suggesting otherwise? 

but in anycase. since i though this was a bug. this is now a feature suggestion

**Comment by noobanidus** [comment]
> https://youtu.be/smrwlq9LaEA?t=2218 why does this then explain that there is such a thing for multiplayer?

He's not suggesting otherwise, he's not talking about security. He's specifically referring to shared networks. i.e., you have a hive network where chests you place show up for other players who are also in your network. This is a convenience thing, if you're sharing a base, etc, not a security thing.

There are currently plenty of chunk protection mods around that prevent players from accessing your chests. If you really want security, you'll need to use something like that for now.

Network security is planned, as Aranai mentioned, for future releases on 1.16+.

**Comment by iceyrazor** [comment]
> > https://youtu.be/smrwlq9LaEA?t=2218 why does this then explain that there is such a thing for multiplayer?
> 
> He's not suggesting otherwise, he's not talking about security. He's specifically referring to shared networks. i.e., you have a hive network where chests you place show up for other players who are also in your network. This is a convenience thing, if you're sharing a base, etc, not a security thing.
> 
> There are currently plenty of chunk protection mods around that prevent players from accessing your chests. If you really want security, you'll need to use something like that for now.
> 
> Network security is planned, as Aranai mentioned, for future releases on 1.16+.

OH ok thanks for clarifying.
