### ISSUE TITLE
Request a "do not sort new items to this chest" checkbox

### ISSUE THREAD

**Issue by gchpaco** [AranaiRa/ArcaneArchives#17]
As I understand it, the algorithm the brazier uses to sort items is

1. if there's a trove and it can fit in it, put it there;
2. if there's a radiant chest that already contains this item and has room for more, put it there;
3. randomly pick some radiant chest with free space.

My usual chest sorting workflow is to have a number of "topic" chests, like mob drops or lumber, and then a catch-all "misc junk" chest.  As such it would be nice to mark all the topic chests as "do not sort items that do not already exist in me", so that the misc junk chests are confined.  As it is if I pull, say, all my iron ingots out for some silly reason and then try to put them back in with the brazier, it is totally random which chest gets them, when I would prefer them to go to the misc junk chest if there is room or to pop out of the brazier if there is not.

**Comment by AranaiRa** [comment]
There's actually a checkbox that prevents Braziers from adding items that a Radiant Chest doesn't already have one of. It's in the next build.

**Comment by duely** [comment]
And I'm pretty sure it works too!
