### ISSUE TITLE
[Suggestion] A method of locking the item type of a radiant trove/tank would be great

### ISSUE THREAD

**Issue by Master00Maniac** [AranaiRa/ArcaneArchives#18]
Similar to the drawer key with storage drawers, being able to lock the type of item that a radiant trove can accept in the event that they become empty via automation would be fantastic. Perhaps in the form of a "Scepter of filtration" or something.

**Comment by duely** [comment]
I'm unwilling to put the effort into doing this simply because I recently put the effort into making it so that empty troves could be piped into and doing so would set the item, whereas previously they had to be "primed". 

But we'll do it at some point.

**Comment by duely** [comment]
Put on the roadmap!
