### ISSUE TITLE
Suggestion: Making slivers of light connect to each other. and gem socket bauble slot adjustable

### ISSUE THREAD

**Issue by SirAron111** [AranaiRa/ArcaneArchives#22]
Making slivers of light connect to each other in various Directions.

Would make placing them or stacking them onto each other look way better as you could make them into a fancy poles or sideways bares and fences.

Also having the gem socked be bound to the body slot is a bit bad as most backpacks and wings and whatever go in there. Making it a ring with a socket or a necklace type item would be better. You could than also have 2 rings and a necklace with a socket at once if possible. (when the system is refined I enabled it during testing to see what it does)

**Comment by duely** [comment]
Slivers of light being able to connect to themselves is actually an unintended feature that will hopefully go away at some point in the future.

The gem socket is an early device specifically designed to go into the body slot for precisely this reason, meaning that you have to make a choice between what you put in that slot.
