### ISSUE TITLE
FakeHandler insertion can potentially void single items when no valid inventory is found

### ISSUE THREAD

**Issue by SirAron111** [AranaiRa/ArcaneArchives#23]
If no valid inventory is present for the Brazier to accept the items you throw in they normally just pop off the flame.

But if you for example attack a hopper or pipe of any kind to it to auto input (works fine as long as radiant chests are near that can accept the items) but when no items can be put in the chests or they are set to only accept items that are already in them. The items just got into the brazier and vanish forever (I set the range down to minimum to make sure they weren’t feed into some random chest somewhere)

This will be a big problem as many people will want to automatically feed into it in some way like from a chest into a hopper into the brazier or with pipes from a dump chest.

So basically it shouldn’t accept auto inputs if no space is available. Maybe by giving it an inventory that it teleports the items from and only if there is space in a hopper/pipe can put something new in.

Also the default range of the brazier is way too big you should let players adjust it upwards and default it to something like 64 at most.

Also it seems like setting the config default for the radiant chests to force set them to no new item accept always sets this setting when a world loads up meaning even if you unlocked a chest it will not stay unlocked and be item specific again. And the other way around to If you set a chest to be only items already inside accepting it unlocks itself when the no new items accept is set to default false.

**Comment by duely** [comment]
Hm, I can see why this would potentially happen. Thanks, I'll look into it!

**Comment by SirAron111** [comment]
Np I am good at finding bugs even if nothing else XD
