### ISSUE TITLE
Bug: Fluid Duplication when transferring fluids from containers via Radiant Amphora

### ISSUE THREAD

**Issue by starji** [AranaiRa/ArcaneArchives#24]
Tested on Arcane Archives 0.2.0.1, Minecraft 1.12.2, Forge version 14.23.5.2836

If you try to move a fluid from a container to a Radiant Tank using a Radiant Amphora, the fluid going into the Radiant Tank is doubled.

Test Scenario:
Using an Immersive Engineering Metal Barrel, add one bucket of water with a vanilla bucket.  Place an empty Radiant Tank and link a Radiant Amphora.  With the Amphora in input mode, right click on the barrel to transfer the water to the tank.  

Expected: The Radiant Tank will contain 1000mb of water

Actual: The Radiant Tank will contain 2000mb of water

I was also able to reproduce this with an Embers Rekindled Fluid Vessel in place of the metal barrel, and when using different fluid types like Liquid Starlight from Astral Sorcery.

**Comment by duely** [comment]
Sorry for the delay in responding! Thank you so much for this information, I will confess that most of the testing I did was with our own tanks... but this is possibly a regression.
