### ISSUE TITLE
Radiant Crafting table's quick craft buttons consume "returned" items

### ISSUE THREAD

**Issue by bshelden** [AranaiRa/ArcaneArchives#25]
When using the quick craft slots on a radiant crafting table, recipes do not return items when the recipe indicates they should.

Ex, quark's rusty iron plate (8x iron ingot + 1 bucket of water) consumes the bucket.  If you craft it normally you get the bucket back.
Blood magic recipes involving the orbs show the same issue.

**Comment by duely** [comment]
The solution here is to limit the quick-crafting slots to IRecipes that are specifically instances of the Minecraft & Forge default recipes (ShapedOreRecipe, etc). Blood Magic orbs specifically, opening a separate issue about buckets.

**Comment by duely** [comment]
Thanks for the report, I'm merging this into #29 as it'll cover both.
