### ISSUE TITLE
Improvement Suggestion: Upgradable Brazier.

### ISSUE THREAD

**Issue by SirAron111** [AranaiRa/ArcaneArchives#33]
Improvement Suggestion: Upgradable brazier.

Currently the Brazier defaults to a giant range higher than the manifest could even check. You should consider making the default something more manageable like 32 blocks range around it. As default!  And you should only be able to adjust this value downwards with the staff.

Instead you should add upgrade slots to it so you can upgrade the max range to 64 with tier 1 to 96 with tier 2 and 128 with max upgrade and maybe add a special upgrade to make it limitless.

As the current default is so immensely high if people live near other players who also use this it can be a  bit tricky. Also its simply lackluster giving this giant range right from the start. If you have such a neat looking upgrade slot system for the trove and tank etc.

You could do the same for the Manifest pedestal tingly giving the manifest itself a small range but making it have a higher range in the form of the stand and making that range upgradable as well.

**Comment by AranaiRa** [comment]
This suggestion honestly feels like upgrades for the sake of upgrades to me, but the note about Brazier range being larger than manifest range is something I hadn't considered.

**Comment by Zieg777** [comment]
Manifest range bugged me anyway. Id suggest bumping that anyway. 

But isn't manifest range a per client config? Or is that server config?

**Comment by AranaiRa** [comment]
Manifest range is indeed a clientside config.

**Comment by SirAron111** [comment]
Ye I noticed all this when testing around that’s also how I found out about the auto inputting bug of the brazier. That one works now pops all things onto the ground if there is no location it can go to XD.
I really do thing the basic range of the brattier needs to go down to minimum 100 at best 64 if the upgrading system doesn’t make it. I mean currently the range is so far you can’t even see the visualized boarders if you don’t play on giant render distance. At least the one when you place it down. You can later adjust it yourself with the staff if you really need high distance.

**Comment by duely** [comment]
You can change the range of the brazier by typing in the box, literally. The current range is defaulted to something quite large for a variety of reasons, and while we might add an upgrade to increase the maximum range, I'm never going to artificially limit it below what it currently has.

Outside of this, I'm sorry, but all of these just sound like personal preferences which can easily be adjusted by changing the range on the brazier and changing the range in the manifest. All of these configuration values will save and be there the next time you load the game.

If I've misunderstood your request, please feel free to comment again.

**Comment by SirAron111** [comment]
Well partly personal preference but also simply the fact that I thought on a multiplayer server if some people are too close to each other and an inexperienced player places a brazier down suddenly his items vanish into the other players chests. I also meant that mostly when placing it down for the first time it shouldn’t default to something high to prevent any unnecessary loadings. And instead be set to something reasonable as you can always, if you need more range if you decide to place a chest further away, increase it with the staff of manipulation afterwards when you need more with no cost anyway. And maybe simply show the min/max range at the side of the manipulation gui.

	The part with the upgrades was just a random idea just ignore it

Well anyway as you say there are reasons why it has to be so large on first place down, I can understand that.

**Comment by AranaiRa** [comment]
This doesn't happen unless players join a combined network using a Letter of Invitation. Braziers can only insert into your network, which by default is only devices you personally placed.

**Comment by duely** [comment]
Although, to be fair, once you are part of a network it defaults to inserting into any available chest on the network. There is functionality to turn that off -- perhaps the logic of that should be reversed, or that should default to on?
