### ISSUE TITLE
Crash when rightclicking a Petal Apothecary with Rivertear

### ISSUE THREAD

**Issue by angelnc1989** [AranaiRa/ArcaneArchives#34]
https://paste.dimdev.org/onowarogoh.mccrash

This crash occurs when I rightclick a Petal Apothecary from Botania with a Rivertear.
The Rivertear also doesn't fill the Petal Apothecary.

**Comment by AranaiRa** [comment]
Looks like you don't have Thaumcraft installed, but do have Botania. Is that correct? The crash is about the Thaumcraft Crucible being missing, so if that's the case I just messed up the check logic a bit.

**Comment by AranaiRa** [comment]
Fixed.

**Comment by angelnc1989** [comment]
> Looks like you don't have Thaumcraft installed, but do have Botania. Is that correct? The crash is about the Thaumcraft Crucible being missing, so if that's the case I just messed up the check logic a bit.

That's correct. :)
