### ISSUE TITLE
Game crash while trying to place radiant resonator

### ISSUE THREAD

**Issue by Paduber** [AranaiRa/ArcaneArchives#36]
Here is the crashlog: https://pastebin.com/PHNjYsXA

Not sure, if it's matter, but other blocks like chests and tanks destroy themselves just after placing down

**Comment by Paduber** [comment]
Problem was sold by just re-logging into launcher 
Sounds like some strange magic, but it works

**Comment by duely** [comment]
Yeah, that's a very strange error message, it doesn't actually say what went wrong -- just that something went wrong...
