### ISSUE TITLE
RClick Thaumcraft's crucible with empty hands fills it with water when AA is installed

### ISSUE THREAD

**Issue by LeoBeliik** [AranaiRa/ArcaneArchives#38]
Right clicking Thaum's crucible auto fills it with water when Arcane Archives is installed.

Arcane Archives 2.0.3
Thaumcraft 6.1.BETA26
Forge 23.5.2838

**Comment by AranaiRa** [comment]
This is a function of having a Rivertear in your inventory. Also works on the Petal Apothecary from Botania.

**Comment by LeoBeliik** [comment]
I don't have the Rivertear.

**Comment by AranaiRa** [comment]
Will look into it.
