### ISSUE TITLE
Friend Can't Log Back in

### ISSUE THREAD

**Issue by Radient-Sora** [AranaiRa/ArcaneArchives#39]
Server Log ISSUE
https://gist.github.com/Radient-Sora/25f3f5f97ee630597c0494a2df766e9e

**Comment by duely** [comment]
I'm not sure why this is happening. I'd recommend restarting the server to flush the null value out of the IteRef list, and I'll adjust the filter... I'm not sure why null is ever ending up in it, which is worriesome.

**Comment by duely** [comment]
I still haven't been able to work out why null entries are going into the tile list. I wrote a hot-fix and deployed it on our server yesterday (as we were noticing the same problem, but it was actually crashing the server) and ran it all of yesterday, and it seems to resolve the symptom. Please check out 0.2.0.5 which was just uploaded to CurseForge.
