### ISSUE TITLE
Unable to apply Trove upgrades

### ISSUE THREAD

**Issue by Zsashas** [AranaiRa/ArcaneArchives#40]
I made a Matrix Brace, but no matter what I do, I can't apply it to the Trove.

**Comment by duely** [comment]
You need to create a Scepter of Manipulation and sneak-right-click the trove to bring up the upgrade interface. I believe this is outlined in the documentation book. I'd recommend also checking out Vallen's video (linked on our CurseForge) page which goes through a number of these systems as well.

**Comment by Zsashas** [comment]
Ah, that would be it. It wasn't mentioned on either the Trove page, or that for the upgrades themselves, and I didn't think to check the other items yet.

**Comment by AranaiRa** [comment]
That's my bad, I'll improve the tome entries to make that clear.
