### ISSUE TITLE
Unable to break scepter of manipulation into essentia in Thaumcraft crucible

### ISSUE THREAD

**Issue by SkyLord-Volmir** [AranaiRa/ArcaneArchives#41]
When using a thaumcraft crucible, I am not able to break a scepter of manipulation into essentia.  I tried both right clicking on the top face of a boiling crucible and dropping into it.  The scepter is not destroyed.  Other arcane archives items (tested with raw radiant quartz) work just fine.

**Comment by duely** [comment]
I can reproduce this although I'm not entirely sure why it's happening. It breaks down fine in the Essentia Smeltery, however, which is the only recommendation I can make. Note that this also happens with mountaintear and rivertear.
