### ISSUE TITLE
Orbs are difficult to distinguish from one another for a colour blind person

### ISSUE THREAD

**Issue by Funwayguy** [AranaiRa/ArcaneArchives#5]
Depending on the type of colour blindness a person has, the orbs become fairly difficult to identify which is which at a glance. One would have to memorise the symbols but even then they fade in and out and aren't easy to make out when dropped. This means picking up the item and using tooltips is the only reliable way of knowing for sure.

Disclaimer: I myself am not colour blind. I simply use the Android dev options on the camera to test.

**Comment by duely** [comment]
We already have a colourblind system that we can apply to this.
