### ISSUE TITLE
Non-stacking items are not able to be inserted into Troves except by one at a time by hand.

### ISSUE THREAD

**Issue by SkyLord-Volmir** [AranaiRa/ArcaneArchives#55]
This bug effects non-stacking items such as identical swords, Reliquary or Quark witch hats, and presumably others.  It was tested on those three somewhat, but mostly on witch hats.
I will explain with Witch Hats as that's where I noticed it.
I setup a voiding Trove with a witch hat in it.
When a witch hat is inserted into a brazier, it goes to an overflow chest, instead of the Trove.
When I have several witch hats in my inventory and I double right click on the trove with an empty hand or another item, no hats are inserted into the Trove.
When I right click (or double right click) on a trove while holding a witch hat, the one in my hand is inserted.
When I set up a hopper to insert witch hats into the trove, they are are not inserted.

**Comment by duely** [comment]
Thinking about it now, I'm betting that the hopper/other methods are going "wait this item doesn't stack" and aren't actually even trying to insert. I'll have to provide an empty slot, which I used to but may have deleted once I changed the access methods to expose all of the contents to the network...

**Comment by duely** [comment]
I can't actually reproduce this specifically with Reliquary witch hats, either with the brazier or with the hopper.... I'll investigate further.

**Comment by duely** [comment]
This is reproducible on the test server, I just haven't had the chance to test it.

**Comment by noobanidus** [comment]
Again, this is definitely a cross-mod interaction, as I just placed a hopper on a trove, primed it with one cake, and then put multiple cakes in the hopper and they all inserted. Likewise, throwing a cake into a nearby brazier also places it in the trove... I'm not sure what could be interfering.
