### ISSUE TITLE
Radiant Amphora has no placement sound and a (slightly?) different pickup sound.

### ISSUE THREAD

**Issue by SkyLord-Volmir** [AranaiRa/ArcaneArchives#58]
Radiant Amphora does not make any sound when placing liquids (tested with water, starlight, and lava)

Radiant Amphora does not make the exact same sound when picking up liquid as a vanilla bucket does.  I think perhaps the bucket is playing two sounds on pickup.  This may be intentional, however, since the 2nd sound is kind of the Minecraft "equip" sound.

**Comment by duely** [comment]
It ... shouldn't be playing any sounds at the minute. I've adjusted it and it'll be on the next version of the Arcane Archives test server, to make it play sounds. However, I'm not differentiating between water/lava, just primarily using water.
