### ISSUE TITLE
Suggestion: Alternate visuals for the Trove so they can stack

### ISSUE THREAD

**Issue by jolandepoel** [AranaiRa/ArcaneArchives#62]
Probably purely visual, but if you place Troves above each other, it looks like the top Trove's base is floating in mid air. As in: the visual is such that the Trove only looks 'correct'/visually logical(?) when placed on a solid surface. 
I was trying to replace a normal "wall of storage drawers" with Troves and it looked... really weird.

It would be cool if the stands in the back could maybe move a little more to the corners and then have four of them so it looks like it's supporting the one above it.
Perhaps the Trove could have it's base to a back wall instead of something beneath it, although that looks weird in other situations. 
It could also look like it's supposed to float in mid air, by removing the solid base? Maybe have a "add this and you can craft it into a floating version" That would look really magical, a wall of Troves (with, of course, those supporting sticks (perhaps connecting to each other?)

I wanted to replace every other row in my wall of Troves with Radiant Quartz slabs as an in between solution, but that doesn't exist yet? Also, connected textures Radiant Quartz blocks (and Chisel variants, perhaps) would be really nice. A girl can dream, right? Especially if all the blocks look like they're straight out of magical fairy land and are gorgeous. 

Grass doesn't stack to more than 64, btw. Also, great work coders, I've added it to a 374 mods pack (Dungeons, Dragons & Space Shuttles + any mod I felt like adding) and nothing broke yet!

**Comment by duely** [comment]
I'm not sure on the visuals at the moment, although variants of Radiant Quartz will most likely come out in a future build.

However, your comment about grass not stacking to higher than 64 confuses me. Do you mean you can only put 64 in a single trove? Or do you mean that you can only put 64 grass in the slots of a Radiant Chest? 

There are a couple of scenarios where the stacking mechanisms are different.

**Comment by jolandepoel** [comment]
I checked: it does stack, it was an interaction with Mouse Tweaks or Inventory Tweaks or something, which causes the grass to go in the chest in stacks of 64 and when middle-click sorting to not automatically make a single stack of more than 64.

**Comment by duely** [comment]
Yeah, that is unfortunately a problem on their end that I haven't really gotten around to discussing with anyone yet.

**Comment by duely** [comment]
At the minute, our focus is on the new models, so I'm archiving this for now, but I'll keep a record of it for later.
