### ISSUE TITLE
Ctrl-Q truncates stack sizes of more than 127 when removing from chests, deleting items

### ISSUE THREAD

**Issue by SkyLord-Volmir** [AranaiRa/ArcaneArchives#63]
If you use ctrl+q to drop a stack of 128 or more items from a radiant chest while standing in front of it and have a Thermal Expansion Satchel set to "Auto-Collect" in your inventory, the itemstack is voided.  You may or may not hear the item pickup noise, but you will not have the items in your inventory or in the satchel.

I tested this with stacks of sizes: 127, 128, 129.  I believe I also lost a 256 stack with this method before.
128 and 129 lose the itemstack.
127 inserts an itemstack of 127 into the satchel, which is odd as it usually cannot have stacks that high.

**Comment by SkyLord-Volmir** [comment]
I forgot: This is for Arcane Archives version 0.2.0.8

**Comment by Tfarcenim** [comment]
I have this issue too, would be interested to know how you fix it.

**Comment by Tfarcenim** [comment]
Hmm, looks like a bug in the satchel code, they assume that if a slot is empty, it sets the count to the max stack size _of the slot_, but this results in deleting the rest if the dropped stack is larger than the max stack size of the slot, here's the culprit.

https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/item/ItemSatchel.java#L316-L318

**Comment by SkyLord-Volmir** [comment]
Tfarcenim: if I read that line right it's copying the ENTIRE itemstack to an empty slot of the satchel then deleting it from the list of things to pick up.  That accounts for why I was able to fill a satchel slot with 127 cobblestone.  
I should also mention that when the satchel is disabled or not on my character, ctrl+q-ing a stack of 128 or 127 out of takes a long time to show up in my inventory and the different stacks may or may not show up at the same time.  So far, however, they've never gotten voided when not being picked up by the satchel.

**Comment by quat1024** [comment]
I wonder if it would be better to make ctrl-dropping just spawn more than one item entity, if that's at all possible.

Minecraft is pretty jank about items stacked to more than 64 anyways (and *especially* about items stacked to more than 127, because item stack size is a signed byte); would probably be a good idea to get rid of overstacked items ASAP when leaving Arcane Archives-controlled areas

**Comment by duely** [comment]
@quat1024 That was entirely my plan. I just haven't worked out which events it's in response to, and how deeply I'll need to dig to ensure it.

**Comment by duely** [comment]
(Interestingly enough, whichever mod (Inventory Tweaks, I think?) does Ctrl-Alt-A to drop everything from your inventory neatly splits itemstacks between entityitems.)
