### ISSUE TITLE
Noise from Radiant Resonator doesn't stop

### ISSUE THREAD

**Issue by Zygus42** [AranaiRa/ArcaneArchives#64]
arcanearchives-0.2.0.8
mysticallib-1.12.2-1.3.5
forge-1.12.2-14.23.5.2838-installer-win

The droning noise from the Radiant Resonator used to stop once the crystal was done.  But now it's constant.  Picked up the Radiant Resonators, but even then the noise continues.

**Comment by duely** [comment]
That's really strange! Was this a resonator placed before updating to 0.2.0.8? I know that there was an issue before that point. Have you tested if waiting until the hum is finished, then placing the resonator down, then placing a block on the resonator stops the sound?

It might just be that the sound is still playing. Outside of that, there might be a regression, but I thought that was something I'd tested.

**Comment by Zygus42** [comment]
Strange - thought I replied to this yesterday.
No.  It was placed with 0.2.0.8.  I picked up the resonators, but the noise continued.  Didn't try placing them down again.  The noise stopped once I logged off and on again.

**Comment by duely** [comment]
Someone, I believe majijn, commented on this earlier implying that it was a cross-mod interaction. I'll try to dig up the post on Discord and dig into it further.

**Comment by majijn** [comment]
i had it happening to me in an instance of electroblob's wizardry that was having known crashes and stuff, some of which were caused by interactions with the sound stuff of the game vs other mods, once i updated to a version that stopped those crashes the resonator also stopped having audio issues,
im using ebwizardry 4.2.2 currently

**Comment by duely** [comment]
So, I can't replicate this in single-player mode or in a server/client mode in a dev environment... It would appear to be an odd interaction with some other mod.

**Comment by duely** [comment]
Please reopen the issue if the above steps/other mod adjustments didn't fix it for you.
