### ISSUE TITLE
Amphora not able to place fluid in the Betweenlands

### ISSUE THREAD

**Issue by Kiyaku** [AranaiRa/ArcaneArchives#67]
Heya,

was running into a bug where i couldn't place any fluid while being in the betweenlands (the tanks where in there as well, clip of it here: https://streamable.com/yei3j, also tried it with vanilla water) .

Placing it in the overworld works just fine (even the swamp water).

Using AA version 0.2.0.9 and BL 3.4.11

Cheers,
SC

**Comment by duely** [comment]
So, context here: there's an issue with using amphorae cross-dimensionally. I may just disable that entirely, so long as it's loaded...
