### ISSUE TITLE
tanks get eaten by the furnace

### ISSUE THREAD

**Issue by majijn** [AranaiRa/ArcaneArchives#69]
tried using up some of my creosote by using it to burn stuff and instead it ate the whole tank

**Comment by duely** [comment]
That is some weird container shit there! I'll definitely have to check it out.

**Comment by duely** [comment]
I've added a container item, @majijn. If you could test if it works, that'd be good. Otherwise... honestly it's not really what I expected to do, I don't know how the tank is set up to handle fluids.

**Comment by majijn** [comment]
cant put it in the furnace at all now! tried with lava, that certainly stops the tanks from being eaten.

**Comment by noobanidus** [comment]
That's strange because nothing I did should've changed that :S
