### ISSUE TITLE
Invalid Mixin Exception Error during startup?

### ISSUE THREAD

**Issue by katubug** [AranaiRa/ArcaneArchives#71]
Hello! I'm combing through all the errors in my excessively large latest.log and came across the following (this is only an excerpt to make things easier to google later):

```
[14:03:22] [main/ERROR] [mixin]: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@c2418b89 from coremod FMLCorePlugin
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@c2418b89 from coremod FMLCorePlugin
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:795) ~[arcanearchives-0.2.0.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) [arcanearchives-0.2.0.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:502) [arcanearchives-0.2.0.9.jar:?]
```

The full excerpt is here: https://pastebin.com/SDtjP5Kn

I also have the full latest.log and debug.log from the same session, if you want them. Perhaps this is nothing? It doesn't seem to have any issues ingame, at least. But it seemed like something I should report.

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.2](http://enthusiasticraft.cf/modpack-update-1-7-2/#modlist)
* **Mod versions:** arcanearchives-0.2.0.9

**Comment by duely** [comment]
Yeah, that's fine, it's just saying that the Mixin transformer is specified to be "client only" but that the server is trying to load it. It should have no negative consequences as nothing actually happens -- I'm just unsure why my classification isn't enough to prevent it on servers...

**Comment by katubug** [comment]
Ah, that makes sense. I didn't parse the "SideTransformer" part, but I see it now. It's out of my depth to suggest anything as to why it is happening though, sorry.

**Comment by duely** [comment]
That's fine, I'm leaving it open because it *is* an issue but it's been bugging me for a while, I've just had other things to focus on.

**Comment by duely** [comment]
I'm doing some testing now, but this could be because the MixinGuiContainer class is flagged as only being loaded on the client-side... I'm not sure how damaging it would be to remove this annotation, but I'll look into it... so far it seems to be relatively safe, so I'll go ahead with it.
