### ISSUE TITLE
Some translation problem and Some bugs「serious or funny」

### ISSUE THREAD

**Issue by xingmot** [AranaiRa/ArcaneArchives#72]
sorry for bad English
I am currently working on the Chinese translation of this mod. It is my great honor to translate such an excellent and beautiful mod.I like it very much!

bugs:
1.radiant resonator can be placed by Better Builder's Wands
and functioning well.
2.The book,some blue font text unable to jump to the appropriate page number
page 8「Radiant Resonator」
page 24「Radiant Crafting Table」「Radiant Resonator」「Slivers of Light」
3.Using a Scepter,sneaking is no need
4.「Chest」and「Trove」can't be upgrade by sneaking using items.
5. Shulker box can't interact with the Hording
6.「Radiant Chest」:
water bucket 1x -> 4x
eggs 16x -> 64x
stone 64x -> 256x
So I think the meaning of the book should be four times, not 256

translation problem
1.The Monitoring Crystal's des,first line can't be translated.
2.The button of Manifest can't be translated.
3.Manifest's interface,items' sneaking tips,「Chest」「Trove」「Monitoring Crystal」
can't be translated.

and some funny:
some animals and mobs think radiant lantern is a block,
They don't try to get through it and step on it then fell down from high place XD

**Comment by duely** [comment]
1. I'll look into this, thank you.
2. I'll pass that to Aranai.
3. It depends on which scepter you use. I will work out precisely the combination of sneaking and not sneaking for each scepter and post it here (we can also update the book).
4. That is a mistake. You upgrade them by sneaking and right-clicking with a "Scepter of Manipulation" to bring up the Upgrade Interface
5. This was disabled (temporarily) as it was causing items to be added to the system but leaving them inside the shulker box, making duplicates of them.
6. That is correct.

Translation problems: I'll look into these, this must be an oversight on my part.

> and some funny:
> some animals and mobs think radiant lantern is a block,
> They don't try to get through it and step on it then fell down from high place XD

This is intentional! :D

**Comment by xingmot** [comment]
My friend suggested that it would be perfect if it could switch on and off the light source XD

**Comment by duely** [comment]
Oh, I misunderstood, I thought you said the radiant resonator. No, that is not intentional -- thank you for that bug report!

**Comment by xingmot** [comment]
I use this search in the vs code
<link ref="[^:]*</link>
and then find more  XD
page 35 manifest:「Monitoring Crystal」
page 42 Devouring Charm:「Parchtear」

**Comment by xingmot** [comment]
I use this search in vscode:
`<link ref="[^:]*</link>`
and then find more XD:
page 35 manifest 「Monitoring Crystal」
page 42 Devouring Charm「Parchtear」

**Comment by xingmot** [comment]
When I open the book, I move and hover the mouse over the page,
I can see another recipe‘s material of another page.

**Comment by duely** [comment]
@xingmot Can you provide a screenshot of this most recent bug?

**Comment by xingmot** [comment]
Virtually any icon on the next page, including the recipe, can be found on the previous page.
Notice the position, this is the next page, it's normal
![image](https://user-images.githubusercontent.com/5901229/66093086-56d8ac00-e5c1-11e9-9e81-5fbeb9454e7c.png)
![image](https://user-images.githubusercontent.com/5901229/66093218-e41c0080-e5c1-11e9-95e1-5d320fd38276.png)
But text messages appear where there are no icon.

**Comment by xingmot** [comment]
![1](https://user-images.githubusercontent.com/5901229/66177346-b1dad380-e693-11e9-8ccf-4d3793655255.png)
XD u know

**Comment by xingmot** [comment]
And the back-side of the Devouring Charm is not mentioned in book. _(:з」∠)_
