### ISSUE TITLE
Sorting using Quark doesn't work anymore

### ISSUE THREAD

**Issue by jesmores** [AranaiRa/ArcaneArchives#74]
arcanearchives-0.2.0.11.jar
Quark-r1.6-177.jar

In case it's relevant:
QuarkOddities-1.12.2.jar
Minecraft Version: 1.12.2
(modded) forge-14.23.5.2847

**Repro Steps**
1. Create a radiant chest
2. Put some items in the radiant chest, mix them up a little
3. Press the Quark sort inventory button

**Expected**
Items rearrange themselves in the chest and get sorted.

**Actual**
Nothing happens

**Notes**
I saw the note about sorting inventory bugs in the known issues, but I don't think this is the same thing. The items aren't disappearing or anything, they're just ... not moving.

Incidentally, the other Quark features such as Merge/Dropoff are working just fine.

**Comment by duely** [comment]
Yeah, sorting doesn't function properly with Quark & Inventory Tweaks because of the expecation that there will only be 64 items per slot, I'm afraid.

**Comment by chillcat222** [comment]
Is it possible this can be fixed? Because it really kills the mod for me and really is the only thing stopping me from using it

**Comment by duely** [comment]
Your best bet would honestly be to file an issue with the Quark & Inventory Tweaks githubs. There are functions to determine the maximum limit of a slot -- which may be more than can be removed from a slot in a single action. I realise that this is me simply passing the buck back onto them, but reintroducing the behaviour where the entire slot's contents could be removed, allowing you to pick up full stacks of 256, causes a number of interface issues and a lot of confusion and frankly isn't really an option for me.

And outside of this solution, there's not really anything that I can do (at least that I'm aware) to better facilitate things. 

I would like to personally reach out to the Inventory Tweaks & Quark teams to discuss it, but my motivation to work on this mod recently has faltered slightly, and I'm not sure what else I can do to make it a possibility.

**Comment by noobanidus** [comment]
I've tried a couple of different things in dev and I can't even get Quark to start sorting let alone mess things up. I don't believe this is a feature we can support from out side.
