### ISSUE TITLE
Throw item in several Brazier of Hoarding

### ISSUE THREAD

**Issue by pawIka** [AranaiRa/ArcaneArchives#76]
If put nearby several Brazier of Hoarding and throw an item at them, then item multiplies in proportion to county of Brazier of Hoarding.
![gif](https://user-images.githubusercontent.com/57269692/68054827-49b5f680-fd00-11e9-9290-3561620e0aba.gif)
Version Forge - 14.23.5.2847
mods:
![image](https://user-images.githubusercontent.com/57269692/68052932-c8f4fb80-fcfb-11e9-9e7e-b147fe09d118.png)

**Comment by duely** [comment]
Hm, I can definitely see how this would happen, I'm obviously failing to check if the entity is dead!

**Comment by LemADEC** [comment]
Any chance for a fix of that dup glitch?
