### ISSUE TITLE
Suggestion: Option to disable getting the book from breaking bookshelves.

### ISSUE THREAD

**Issue by SirAron111** [AranaiRa/ArcaneArchives#78]
Suggestion: Option to disable getting the book from breaking bookshelves.

I think having an option to disable the way to get the book by simply breaking a bookshelf somewhere should be an option. To enable pack makers to provide a custom means via a recipe or a book integration etc to unlock this knowledge in a different way.

**Comment by AranaiRa** [comment]
That's an excellent idea, I hadn't considered pack makers' needs there.
