### ISSUE TITLE
Bug: Server crash when feeding non stackable items into the brazier with a hopper.

### ISSUE THREAD

**Issue by SirAron111** [AranaiRa/ArcaneArchives#80]
Bug: Server crash when feeding non stackable items into the brazier with a hopper and the chest they get sorted into is full. (the non stackable items still stack up in the chests to the maximum set amount meaning if set to 8 item stacks max the non stackable items in this case the totems from everlasting abilities, will stack up to 8 each counting as a full stack) and if the brazier tries to send it to the full chest when there are already all spots taken and no stacks free, it gets stuck in the hopper and crashes.
https://pastebin.com/n4pCmT1i

**Comment by duely** [comment]
I'm unable to reproduce this in a dev environment with a full radiant chest with 4 swords in one slot, feeding swords into a hopper, with the hopper feeding into a brazier.

Looking at the crash, it seems to be the issue that marking the tile as dirty after updating the comparator output level is hanging on `getBlockState` which really shouldn't be the case. However, I'll wrap those lines to only occur after a successful insertion.

I'm going to presume there are deeper problems at issue here, but having seen first-hand the dangers of item copying during insert handlers from just trying to hopper eggs into an empty diamond chest, I can understand that it might end up being hard on the server for some reason.

**Comment by SirAron111** [comment]
i did upgrade the configs so they normaly can hold 512 items (8 stacks) maybe thats had soemthing to do with it.
