### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by djalalytdin** [AranaiRa/ArcaneArchives#81]
when trying to put a radiant resonator, minecraft crashes (I play with the assembly of mods)
![SzbEOPcBdcE](https://user-images.githubusercontent.com/59488388/71749830-9eecc080-2e87-11ea-9963-05e766b3baa7.jpg)

**Comment by Davoleo** [comment]
oof, optifine

**Comment by noobanidus** [comment]
Does it work without OptiFine?

**Comment by noobanidus** [comment]
Okay, upon further inspection, literally the only way this crash could happen is if you have an invalid or null UUID. That will never happen on a normal copy of Minecraft, so I can only presume you are using a cracked launcher of some description -- and that is why you only shared the top part of the crash report.

If I'm incorrect and you *are* using an actual copy of Minecraft, please comment again with the full crash report and I'll re-open the issue.

**Comment by djalalytdin** [comment]
Извините, что отвечаю поздно. Теперь я скажу как можно больше деталей. Во-первых, я не понимаю коды модов, я только что связался со службой технической поддержки сборки модов (этот мод разбился в сборке), где мне прислали это фото Выделенная ошибка. Так как я не понял, в чем проблема, я написал вам. Я скачал эту сборку в описании под видео от одного известного российского блогера (Mr.lololoshka). Если вы хотите скачать ее и посмотреть, что за проблема в том, что вот ссылка: [Извините, что отвечаю поздно. Теперь я скажу как можно больше деталей. Во-первых, я не понимаю коды модов, я только что связался со службой технической поддержки сборки модов (этот мод разбился в сборке), где мне прислали это фото Выделенная ошибка. Так как я не понял, в чем проблема, я написал вам. Я скачал эту сборку в описании под видео от одного известного российского блогера (Mr.lololoshka). Если вы хотите скачать ее и посмотреть, что за проблема в том, что вот ссылка: [Извините, что отвечаю поздно. Теперь я скажу как можно больше деталей. Во-первых, я не понимаю коды модов, я только что связался со службой технической поддержки сборки модов (этот мод разбился в сборке), где мне прислали это фото Выделенная ошибка. Так как я не понял, в чем проблема, я написал вам. Я скачал эту сборку в описании под видео от одного известного российского блогера (Mr.lololoshka). Если вы хотите скачать ее и посмотреть, что за проблема в том, что вот ссылка: https://drive.google.com/file/d/1RLelMkcsjEEncndFDs3KHCQPxHZufX0s/view?usp=sharing](url)
