### ISSUE TITLE
right clicking output slot of gemcutter's table

### ISSUE THREAD

**Issue by majijn** [AranaiRa/ArcaneArchives#85]
on recipes with multiple item outputs (such as devouring charms) causes the recipe to eat the ingredients but only give half the output

dunno how this can be fixed

**Comment by noobanidus** [comment]
Hm. Yeah, that's not something that I expected.

Crafting output slots ... actually, I think the crafting table does this but *doesn't* give you only half the output. I'll need to actually reimplement this as a proper crafitng output slot in the rewrite.
