### ISSUE TITLE
Making an Existing Chest Radiant Doesn't Add it to the Network

### ISSUE THREAD

**Issue by Crazydude323** [AranaiRa/ArcaneArchives#86]
Recently started up Arcane Archives, and for whatever reason, shift + R-Clicking a chest with radiant quartz to turn it into a radiant chest doesn't add it to the network. Placing the chest down by hand works just fine, however. It's more of an inconvenience than anything, but some of my chests are quite full, so it'd be nice if there was a fix for this besides breaking and replacing them.

**Comment by Crazydude323** [comment]
I just used the Debug Orb to check, and it printed out these two logs:
https://paste.dimdev.org/cinoqabawa.debugClient
https://paste.dimdev.org/okesijudam.debugServer

The network UUID is my UUID on the server, so that part looks fine actually. The only difference is that, on the Client side, it doesn't seem to be part of the "network tile list". I assume that's the issue?

**Comment by noobanidus** [comment]
Are you in single-player or multiplayer? Are you part of a network?

The Network Tile List only exists on the server-side, so it's not something you need to worry about.

Obviously, have you tried relogging?

**Comment by Crazydude323** [comment]
Multiplayer server, and I assume that I'm part of a network (like I said, any Radiant Chest that I put down manually connects to my Manifest just fine).

I actually didn't even think to try re-logging; I'll try that the next time I make a radiant chest and see if it fixes the issue.

Thanks for the quick resposne, by the way!

**Comment by noobanidus** [comment]
Also, what version are you running?

**Comment by Crazydude323** [comment]
Running 0.2.0.15. I'll be on the server later today, so I'll test if relogging fixes the issue.

**Comment by Crazydude323** [comment]
Finally got a chance to test, and no, relogging doesn't fix the issue.

**Comment by noobanidus** [comment]
I'm not able to actually replicate this with (a slightly variant) 0.2.0.15 either in multiplayer or on a server. I'm gonna guess it's some sort of cross-mod interaction as it works perfectly fine with vanilla chests in my dev environment/dev server + dev client.
