### ISSUE TITLE
[Suggestion] Way to exclude specific blocks from a network

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [AranaiRa/ArcaneArchives#87]
Sorry if this is the wrong place for suggestions, figured I might as well try here.

It would be nice to have a way to exclude blocks from the network; I like using the crates for general utility, but I would not want their contents to show up in my manifest. For example, if I dedicate to using the arcane archives network for exclusively Thaumcraft stuff, I wouldnt want to have other arcane archive chests that DONT contain thaumcraft stuff to show up in the manifest.

**Comment by AranaiRa** [comment]
This is already planned actually.
