### ISSUE TITLE
Locked+Empty trove doesn't accept item from brazier.

### ISSUE THREAD

**Issue by kurosnow** [AranaiRa/ArcaneArchives#88]
We have an EnderIO Reinforced Autocrafting setup with Simple Storage Network and Cyclic, but when we put it hooked up to a trove, in particular the one that "jams" is the dark steel, it'll pull till 0 items remain, and despite having the trove locked with a radiant key, when it's empty, the braziers will put the dark steel into a radiant chest until the trove contains at least 1 item, inserted by hand.

Expected: The dark steel would go into the trove locked to dark steel, even when the trove is empty.

MC 1.12.2, Arcane Archives 0.2.0.15

**Comment by noobanidus** [comment]
The main issue here is the fact that the comparison takes place against a 0-count item which is equated to null. I'll manually write a comparator that allows for checking against potentially "empty" itemstacks.
