### ISSUE TITLE
 Incompatibility with vanillafix

### ISSUE THREAD

**Issue by A-So-Nya** [AranaiRa/ArcaneArchives#89]
Crash on minecraft startup due to old Mixins
mods:
arcane archives 0.2.0.16
mysticallib 1.7.0
vanillafix 1.0.10-150
latest.log:
https://pastebin.com/QuhMM7nu

**Comment by noobanidus** [comment]
You need to file this bug with VanillaFix.

**Comment by A-So-Nya** [comment]
Sorry, English isn't my native language and i don't fully understand what "file" means here
Here's where i took last VanillaFix https://www.curseforge.com/minecraft/mc-mods/vanillafix/files/2915154
Here's my issue to them with the same information https://github.com/DimensionalDevelopment/VanillaFix/issues/240

**Comment by noobanidus** [comment]
Ah, my mistake, I misunderstood the issue.
