### ISSUE TITLE
crash when upgrading from 0.2.0.16 to 0.2.0.17

### ISSUE THREAD

**Issue by pibblesarethebest** [AranaiRa/ArcaneArchives#90]
[crash-2020-03-28_20.56.09-client.txt](https://github.com/AranaiRa/ArcaneArchives/files/4398153/crash-2020-03-28_20.56.09-client.txt)

**Comment by noobanidus** [comment]
Hm, I may have messed something up. Thanks for the quick report!

**Comment by noobanidus** [comment]
This appears to be a conflict with another mod, I'm not sure which one though.

**Comment by noobanidus** [comment]
If necessary, you can downgrade to 0.2.0.16, as the only difference is the update to Mixins.
