### ISSUE TITLE
Manifest Lectern Should Function Like an ME Terminal

### ISSUE THREAD

**Issue by vizthex123** [AranaiRa/ArcaneArchives#94]
Title. It should let you take items out and place them into the system, maybe increase the crafting cost to compensate for the balance shift.

**Comment by noobanidus** [comment]
Please see previous issues on this topic; this isn't the intent of the lectern.

**Comment by AranaiRa** [comment]
To further elaborate, the manifest and lectern are intended for very early game use. They're a major improvement over vanilla sorting, but don't have the complete convenience of a full I/O system.

An upcoming device much later in ArcArc's internal progression is intended to allow for actual one stop I/O.
