### ISSUE TITLE
Some radiant chest can't having name

### ISSUE THREAD

**Issue by Zarpyk** [AranaiRa/ArcaneArchives#96]
I can't put name or item on some radiant chest, but others chets work fine
ErrorLog: https://gist.github.com/GuerreroCraft61/845ad812a9ab8efe67e3c5aa028c8be8

**Comment by noobanidus** [comment]
Does this happen without Sponge?

**Comment by noobanidus** [comment]
So, this appears to be a tile entity that doesn't properly exist or cannot be resolved on the server. I'd recommend breaking the tile and re-placing it. I've added a more informative message in the next release.
