### ISSUE TITLE
java.lang.RuntimeException: Attempted to load class chd for invalid side SERVER

### ISSUE THREAD

**Issue by ErikSteiner** [AranaiRa/ArcaneArchives#97]
I am not sure if this is related to your mod. I just scrolled through the log file of the server version of Rebirth of the night and found this exception at startup. The server will continue, so it doesn't seem critical. However to be on the save side, I attached the log file.
`[22:06:39] [main/TRACE] [mixin]: Catching
net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@71f96dfb from coremod FMLCorePlugin
Caused by: java.lang.RuntimeException: Attempted to load class chd for invalid side SERVER
`
[chd_invalid.txt](https://github.com/AranaiRa/ArcaneArchives/files/4691642/chd_invalid.txt)

**Comment by noobanidus** [comment]
This can generally be safely ignored.

**Comment by ErikSteiner** [comment]
Thank you for your quick reply.
