### ISSUE TITLE
Crash with Mowzies mobs.

### ISSUE THREAD

**Issue by SirAron111** [AranaiRa/ArcaneArchives#98]
Error with Mowzies mobs. I am not sure what it is but here is the link to mowzies explanation. Hope that helps.

https://github.com/BobMowzie/MowziesMobs/issues/224#event-3408072388

**Comment by Sunconure11** [comment]
I can confirm the same issue.

https://pastebin.com/7jt3RzzK

**Comment by noobanidus** [comment]
@SirAron111 @Sunconure11 This is actually an issue with Mowzie's Mobs. They were passing a null value where a null value should never be passed, and it appears to have been fixed a day or two ago in [this commit](https://github.com/BobMowzie/MowziesMobs/commit/689e99e83430792ee51901c8191e916334dc6029). These was also a recent release on CurseForge...
