### ISSUE TITLE
Crash with Just Enough IDs

### ISSUE THREAD

**Issue by xingmot** [AranaiRa/ArcaneArchives#99]
This is the problem I encountered while making the modpack, and the crash report is similar to the No SuchField Exception that other players in the issue encountered. 
Asked about some programmers who were also in the field, I learned that two mixins appeared in my modpack, one jeID and the other of Arcane Archives. 
This error was caused by The Arcane Archives loading before the jeID. Modifying jeIDxxx.jar to AAAAAJeIDxxxx.jar can solve this problem, or use a nonlib version of jeID. 
But I don't think this problem is present in other mod, so I'm suggesting here that the author can modify the internal code or make appropriate changes to the published file name.

**Comment by noobanidus** [comment]
There are multiple versions of Arcane Archives available in order to help with the issues of conflicts of Mixins versions. Please try one of the others presented.
